# Generated by Django 5.2.7 on 2025-11-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО студента')),
                ('subject', models.CharField(max_length=20, verbose_name='Предмет')),
                ('grade', models.CharField(max_length=20, verbose_name='Оценка')),
                ('date', models.DateField(verbose_name='Дата оценки')),
                ('teacher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Преподаватель')),
                ('cafedra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'db_table': 'studstat',
                'unique_together': {('name',)},
            },
        ),
    ]
