# Generated by Django 5.2.7 on 2025-11-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studStat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statstudent',
            unique_together={('name', 'subject', 'grade', 'date')},
        ),
    ]
